/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as AuthenticatedDefinitionsIndexRouteImport } from './routes/_authenticated/definitions/index'
import { Route as AuthenticatedDefinitionsCreateIndexRouteImport } from './routes/_authenticated/definitions/create/index'
import { Route as AuthenticatedDefinitionsDefinitionIdIndexRouteImport } from './routes/_authenticated/definitions/$definitionId/index'
import { Route as AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRouteImport } from './routes/_authenticated/definitions/$definitionId/runtime/$runtimeId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDefinitionsIndexRoute =
  AuthenticatedDefinitionsIndexRouteImport.update({
    id: '/definitions/',
    path: '/definitions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDefinitionsCreateIndexRoute =
  AuthenticatedDefinitionsCreateIndexRouteImport.update({
    id: '/definitions/create/',
    path: '/definitions/create/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDefinitionsDefinitionIdIndexRoute =
  AuthenticatedDefinitionsDefinitionIdIndexRouteImport.update({
    id: '/definitions/$definitionId/',
    path: '/definitions/$definitionId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRoute =
  AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRouteImport.update({
    id: '/definitions/$definitionId/runtime/$runtimeId/',
    path: '/definitions/$definitionId/runtime/$runtimeId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/definitions': typeof AuthenticatedDefinitionsIndexRoute
  '/definitions/$definitionId': typeof AuthenticatedDefinitionsDefinitionIdIndexRoute
  '/definitions/create': typeof AuthenticatedDefinitionsCreateIndexRoute
  '/definitions/$definitionId/runtime/$runtimeId': typeof AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/definitions': typeof AuthenticatedDefinitionsIndexRoute
  '/definitions/$definitionId': typeof AuthenticatedDefinitionsDefinitionIdIndexRoute
  '/definitions/create': typeof AuthenticatedDefinitionsCreateIndexRoute
  '/definitions/$definitionId/runtime/$runtimeId': typeof AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in/': typeof SignInIndexRoute
  '/_authenticated/definitions/': typeof AuthenticatedDefinitionsIndexRoute
  '/_authenticated/definitions/$definitionId/': typeof AuthenticatedDefinitionsDefinitionIdIndexRoute
  '/_authenticated/definitions/create/': typeof AuthenticatedDefinitionsCreateIndexRoute
  '/_authenticated/definitions/$definitionId/runtime/$runtimeId/': typeof AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/definitions'
    | '/definitions/$definitionId'
    | '/definitions/create'
    | '/definitions/$definitionId/runtime/$runtimeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/definitions'
    | '/definitions/$definitionId'
    | '/definitions/create'
    | '/definitions/$definitionId/runtime/$runtimeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in/'
    | '/_authenticated/definitions/'
    | '/_authenticated/definitions/$definitionId/'
    | '/_authenticated/definitions/create/'
    | '/_authenticated/definitions/$definitionId/runtime/$runtimeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/definitions/': {
      id: '/_authenticated/definitions/'
      path: '/definitions'
      fullPath: '/definitions'
      preLoaderRoute: typeof AuthenticatedDefinitionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/definitions/create/': {
      id: '/_authenticated/definitions/create/'
      path: '/definitions/create'
      fullPath: '/definitions/create'
      preLoaderRoute: typeof AuthenticatedDefinitionsCreateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/definitions/$definitionId/': {
      id: '/_authenticated/definitions/$definitionId/'
      path: '/definitions/$definitionId'
      fullPath: '/definitions/$definitionId'
      preLoaderRoute: typeof AuthenticatedDefinitionsDefinitionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/definitions/$definitionId/runtime/$runtimeId/': {
      id: '/_authenticated/definitions/$definitionId/runtime/$runtimeId/'
      path: '/definitions/$definitionId/runtime/$runtimeId'
      fullPath: '/definitions/$definitionId/runtime/$runtimeId'
      preLoaderRoute: typeof AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDefinitionsIndexRoute: typeof AuthenticatedDefinitionsIndexRoute
  AuthenticatedDefinitionsDefinitionIdIndexRoute: typeof AuthenticatedDefinitionsDefinitionIdIndexRoute
  AuthenticatedDefinitionsCreateIndexRoute: typeof AuthenticatedDefinitionsCreateIndexRoute
  AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRoute: typeof AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDefinitionsIndexRoute: AuthenticatedDefinitionsIndexRoute,
  AuthenticatedDefinitionsDefinitionIdIndexRoute:
    AuthenticatedDefinitionsDefinitionIdIndexRoute,
  AuthenticatedDefinitionsCreateIndexRoute:
    AuthenticatedDefinitionsCreateIndexRoute,
  AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRoute:
    AuthenticatedDefinitionsDefinitionIdRuntimeRuntimeIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
